# Generated by Django 3.2.6 on 2021-11-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept_list_citizen',
            name='category',
        ),
    ]
