# Generated by Django 3.1.13 on 2021-10-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dept_hseb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1', models.CharField(max_length=50)),
                ('img_1', models.ImageField(upload_to='static/img/dept1/hseb')),
            ],
        ),
    ]
