# Generated by Django 3.1.13 on 2021-10-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dept_hseb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='static/img/dept1/hseb')),
            ],
            options={
                'verbose_name_plural': 'hseb_department',
            },
        ),
        migrations.CreateModel(
            name='student_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_student_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('eleven_sym', models.IntegerField()),
                ('twelve_sym', models.IntegerField()),
                ('img', models.ImageField(upload_to='static/img/dept1/student_hseb')),
            ],
            options={
                'verbose_name_plural': 'student_main_hseb',
            },
        ),
    ]
