# Generated by Django 3.1.13 on 2021-10-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hseb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dept_hseb',
            options={'verbose_name_plural': 'hseb_department'},
        ),
    ]
