# Generated by Django 3.1.13 on 2021-10-17 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_citizen'),
        ('hseb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_main',
            name='citizen_student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.citizen'),
        ),
    ]
