# Generated by Django 3.1.13 on 2021-09-30 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='HSEB',
        ),
        migrations.RenameModel(
            old_name='Employee',
            new_name='TU',
        ),
        migrations.RenameField(
            model_name='hseb',
            old_name='location',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='tu',
            old_name='designation',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_hseb',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_tu',
        ),
    ]
