# Generated by Django 3.1.13 on 2021-10-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hseb', '0002_auto_20211003_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept_hseb',
            old_name='img_1',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='dept_hseb',
            old_name='name_1',
            new_name='name',
        ),
    ]
