# Generated by Django 3.1.13 on 2021-09-30 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210930_1155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TU',
            new_name='tribhuwan_university',
        ),
    ]
