# Generated by Django 3.1.13 on 2021-10-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseb', '0002_auto_20211017_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_main',
            name='faculty',
            field=models.CharField(default='', max_length=20),
        ),
    ]
