# Generated by Django 3.1.13 on 2021-10-17 04:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_citizen'),
        ('hseb', '0003_student_main_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='science_class_12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phy', models.FloatField(validators=[django.core.validators.MaxValueValidator(75)])),
                ('phy_prac', models.FloatField(validators=[django.core.validators.MaxValueValidator(25)])),
                ('math', models.FloatField(validators=[django.core.validators.MaxValueValidator(75)])),
                ('math_prac', models.FloatField(validators=[django.core.validators.MaxValueValidator(25)])),
                ('chem', models.FloatField(validators=[django.core.validators.MaxValueValidator(75)])),
                ('chem_prac', models.FloatField(validators=[django.core.validators.MaxValueValidator(25)])),
                ('english', models.FloatField(validators=[django.core.validators.MaxValueValidator(75)])),
                ('english_prac', models.FloatField(validators=[django.core.validators.MaxValueValidator(25)])),
                ('nep', models.FloatField(validators=[django.core.validators.MaxValueValidator(75)])),
                ('nep_prac', models.FloatField(validators=[django.core.validators.MaxValueValidator(25)])),
                ('bio', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(75)])),
                ('bio_prac', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(25)])),
                ('comp', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(75)])),
                ('comp_prac', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(25)])),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('result', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('slug', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.citizen')),
            ],
            options={
                'verbose_name_plural': 'student hseb 12 marks',
            },
        ),
    ]
