# Generated by Django 3.1.13 on 2021-10-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseb', '0003_auto_20211003_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_student_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('eleven_sym', models.IntegerField()),
                ('twelve_sym', models.IntegerField()),
                ('img', models.ImageField(upload_to='static/img/dept1/student_hseb')),
            ],
            options={
                'verbose_name_plural': 'student_main_hseb',
            },
        ),
        migrations.CreateModel(
            name='student_marks_eleven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phy', models.FloatField()),
                ('math', models.FloatField()),
                ('chem', models.FloatField()),
                ('english', models.FloatField()),
                ('nep', models.FloatField()),
                ('bio', models.FloatField()),
                ('comp', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hseb.student_main')),
            ],
        ),
    ]
