# Generated by Django 3.1.13 on 2021-10-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseb', '0004_student_main_student_marks_eleven'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_marks_twelve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phy', models.FloatField()),
                ('math', models.FloatField()),
                ('chem', models.FloatField()),
                ('english', models.FloatField()),
                ('nep', models.FloatField()),
                ('bio', models.FloatField()),
                ('comp', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hseb.student_main')),
            ],
        ),
    ]
