# Generated by Django 3.1.13 on 2021-09-30 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210930_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hseb',
            options={'verbose_name_plural': 'HSEB'},
        ),
        migrations.AlterModelOptions(
            name='tribhuwan_university',
            options={'verbose_name_plural': 'tribhuwan_university'},
        ),
    ]
