# Generated by Django 3.1.13 on 2021-10-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseb', '0005_science_class_11'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept_hseb',
            name='slug',
            field=models.CharField(default='', max_length=10),
        ),
    ]
