# Generated by Django 3.1.13 on 2021-09-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210930_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hseb',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='tribhuwan_university',
            name='location',
        ),
        migrations.AddField(
            model_name='hseb',
            name='address',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='hseb',
            name='citizenship_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tribhuwan_university',
            name='address',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tribhuwan_university',
            name='citizenship_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='hseb',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tribhuwan_university',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
