# Generated by Django 3.1.13 on 2021-10-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseb', '0006_dept_hseb_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_hseb',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
