# Generated by Django 3.1.13 on 2021-10-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hseb', '0007_auto_20211018_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_main',
            old_name='citizen_student_id',
            new_name='citizen_student',
        ),
    ]
