# Generated by Django 3.1.13 on 2021-10-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseb', '0008_auto_20211018_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_main',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
