# Generated by Django 3.2.6 on 2021-11-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseb', '0011_auto_20211114_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mgmt_class_12',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student_main',
            name='twelve_sym',
        ),
        migrations.AlterField(
            model_name='student_main',
            name='sym_no',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='mgmt_class_11',
        ),
        migrations.DeleteModel(
            name='mgmt_class_12',
        ),
    ]
