# Generated by Django 3.2.6 on 2021-11-16 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseb', '0012_auto_20211114_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='science_class_11',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hseb.student_main'),
        ),
        migrations.AlterField(
            model_name='science_class_12',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hseb.student_main'),
        ),
    ]
