# Generated by Django 3.2.6 on 2021-11-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseb', '0013_auto_20211116_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_main',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
