# Generated by Django 3.1.13 on 2021-10-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_citizen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='citizenship_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
