# Generated by Django 3.2.6 on 2021-11-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211113_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='citizenship_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
