# Generated by Django 3.2.6 on 2021-11-20 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211120_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='citizen',
            name='birthplace',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='citizen',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='citizen',
            name='district',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='citizen',
            name='fathers_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='citizen',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='citizen',
            name='mothers_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='citizen',
            name='nagrita_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='citizen',
            name='spouse_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='citizen',
            name='ward_no',
            field=models.CharField(default='', max_length=100),
        ),
    ]
