# Generated by Django 3.2.6 on 2021-11-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211120_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='img',
            field=models.ImageField(default='', upload_to='static/img/dept1/student_hseb'),
        ),
    ]
