# Generated by Django 3.1.13 on 2021-10-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='static/img/dept1')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('category', models.CharField(choices=[('education', 'education'), ('transportation', 'transportation'), ('health', 'health'), ('security', 'security'), ('online_form', 'online_form'), ('online_verify', 'online_verify')], default='', max_length=30)),
            ],
        ),
    ]
