# Generated by Django 3.1.12 on 2021-09-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_list', '0003_auto_20210916_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_list',
            name='category',
            field=models.CharField(choices=[('education', 'education'), ('transportation', 'transportation'), ('health', 'health'), ('security', 'security'), ('online_form', 'online_form'), ('online_verify', 'online_verify')], default='', max_length=30),
        ),
    ]
