# Generated by Django 3.1.12 on 2021-09-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_list', '0005_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name1',
        ),
        migrations.AddField(
            model_name='customuser',
            name='category',
            field=models.CharField(choices=[('education', 'education'), ('transportation', 'transportation'), ('health', 'health'), ('security', 'security')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
