# Generated by Django 3.1.12 on 2021-09-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_list', '0006_auto_20210923_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept_list',
            name='name1',
            field=models.CharField(default='', max_length=50),
        ),
    ]
