# Generated by Django 3.1.12 on 2021-09-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_list', '0007_dept_list_name1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept_list',
            name='name1',
        ),
        migrations.AddField(
            model_name='dept_list',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
