# Generated by Django 3.1.13 on 2021-09-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept_list', '0008_auto_20210924_0923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
