# Generated by Django 3.2.6 on 2021-11-13 03:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211113_0940'),
        ('tribhuwan_university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_tu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='csit_subj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phy', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(60)])),
                ('phy_prac', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(40)])),
                ('digitallogic', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(60)])),
                ('digitallogic_prac', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(40)])),
                ('math', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(80)])),
                ('math_prac', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(20)])),
                ('c_program', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(60)])),
                ('c_program_prac', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(40)])),
                ('iit', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(60)])),
                ('iit_prac', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(40)])),
                ('slug', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.citizen')),
            ],
        ),
    ]
