# Generated by Django 3.2.6 on 2021-11-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211113_0940'),
        ('tribhuwan_university', '0002_auto_20211113_0940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='csit_subj',
            new_name='csit_subj1',
        ),
    ]
