# Generated by Django 3.1.13 on 2021-09-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210930_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tribhuwan_university',
            options={'verbose_name_plural': 'Comments'},
        ),
    ]
