# Generated by Django 3.2.6 on 2021-11-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribhuwan_university', '0003_rename_csit_subj_csit_subj1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csit_subj1',
            options={'verbose_name_plural': 'csit subjects'},
        ),
        migrations.AddField(
            model_name='csit_subj1',
            name='percentage',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='csit_subj1',
            name='result',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
