# Generated by Django 3.2.6 on 2021-11-16 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211113_0940'),
        ('tribhuwan_university', '0004_auto_20211114_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csit_subj1',
            options={'verbose_name_plural': 'csit 1st sem'},
        ),
        migrations.CreateModel(
            name='student_main_tu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sym_no', models.CharField(max_length=50)),
                ('faculty', models.CharField(default='', max_length=20)),
                ('img', models.ImageField(upload_to='static/img/dept1/student_hseb')),
                ('slug', models.SlugField(blank=True, default='', max_length=10, null=True)),
                ('citizen_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.citizen')),
            ],
            options={
                'verbose_name_plural': 'student_main_tu',
            },
        ),
        migrations.AlterField(
            model_name='csit_subj1',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tribhuwan_university.student_main_tu'),
        ),
    ]
