# Generated by Django 3.2.6 on 2021-11-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribhuwan_university', '0005_auto_20211116_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept_tu',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
