# Generated by Django 3.2.6 on 2021-11-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribhuwan_university', '0006_dept_tu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='csit_subj1',
            name='result2',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='csit_subj1',
            name='result3',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='csit_subj1',
            name='result4',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='csit_subj1',
            name='result5',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='csit_subj1',
            name='result6',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='csit_subj1',
            name='result7',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='csit_subj1',
            name='result8',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
